config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	get "insurance" => "insurance#home"
	namespace :insurance do 
		get "auto"
		get "commercial"
		get "life" 
		get "health" 
		get "motorcycle"
		get "flood" 
		get "boat"
		get "condo"
		get "renters" 
		get "landlord" 
		get "jewelry"
	end 

	get "quote" => 'quote#index'

	get "whoweare" => 'whoweare#index'
			
	get 'welcome/index'
	root 'welcome#index'

	resources :quotes, only: [:create]
end

app/models/additional_insured.rb
class AdditionalInsured < ActiveRecord::Base
  belongs_to :quote, inverse_of: :additional_insureds
  validates :name, :birthday, presence: true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auto_quote.rb
class AutoQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/boat_quote.rb
class BoatQuote < Quote
  validates :first_name, :last_name, presence: true
end

app/models/commercial_quote.rb
class CommercialQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, :commercial_business_type, presence: true
end

app/models/condo_quote.rb
class CondoQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :quote, inverse_of: :drivers
  validates :first_name, :last_name, presence: true
end

app/models/flood_insurance_quote.rb
class FloodInsuranceQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/jewelry_quote.rb
class JewelryQuote < Quote
  validates :first_name, :last_name, presence: true
end

app/models/landlord_quote.rb
class LandlordQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/life_insurance_quote.rb
class LifeInsuranceQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/motorcycle_quote.rb
class MotorcycleQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/property_quote.rb
class PropertyQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many :drivers, inverse_of: :quote
  has_many :vehicles, inverse_of: :quote
  has_many :additional_insureds, inverse_of: :quote
  has_many :valuable_items, inverse_of: :quote

  strip_attributes
  validates :email, :phone, presence: true


  mount_uploader :current_policy, CurrentPolicyUploader
  
  after_create :notify_email

  def pretty_date
    created_at.strftime("%m/%d/%Y")
  end

  accepts_nested_attributes_for :drivers, :vehicles, :additional_insureds, :valuable_items

  def name
    if name_of_insured.present?
      name_of_insured
    else
      "#{first_name} #{last_name}"
    end
  end

  def pretty_date
    created_at.strftime('%m-%d-%Y')
  end

private
  # Send a notification email
  def notify_email
    begin
      QuoteMailer.send_email(self).deliver
    rescue => e
      Rails.logger.error("Unable to send quote email notification. #{e.message}")
    end
  end
end

app/models/renters_quote.rb
class RentersQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/valuable_item.rb
class ValuableItem < ActiveRecord::Base
  belongs_to :quote, inverse_of: :valuable_items
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :quote, inverse_of: :vehicles
end

app/controllers/quote_controller.rb
class QuoteController < ApplicationController
  def index
    @type = params[:type] || "PropertyQuote"
    @quote = @type.classify.constantize.new
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  TYPE_TO_PATH_MAPPING = {
    "PropertyQuote" => "insurance/home",
    "AutoQuote" => "insurance/auto",
    "CommercialQuote" => "insurance/commercial",
    "LifeInsuranceQuote" => "insurance/life",
    "HealthInsuranceQuote" => "insurance/health",
    "MotorcycleQuote" => "insurance/motorcycle",
    "FloodInsuranceQuote" => "insurance/flood",
    "BoatQuote" => "insurance/boat",
    "CondoQuote" => "insurance/condo",
    "RentersQuote" => "insurance/renters",
    "LandlordQuote" => "insurance/landlord",
    "JewelryQuote" => "insurance/jewelry",
    "Contact" => "whoweare/#index"
  }

  respond_to :html

  def create
    @quote = params[:quote].permit(:type)["type"].constantize.new(permitted_params)
    @quote.save
    
    if session[:in_quote_form]
      @type = params[:quote].permit(:type)["type"]
      render "quote/index"
    else
      render TYPE_TO_PATH_MAPPING[@quote.type]
      TYPE_TO_PATH_MAPPING[@quote.type] =~ /\/(.*)/
      @action_name = $1
    end
  end

  private

  def permitted_params
    params.require(:quote).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def phone_number_link(text)
    sets_of_numbers = text.scan(/[0-9]+/)
    number = "+1-#{sets_of_numbers.join('-')}"
    link_to text, "tel:#{number}"
  end

  def gender_collection
    ["Male", "Female"]
  end

  def yes_no_collection
    ["Yes", "No"]
  end

  def auto_bodily_injury_per_person_collection
    ["$25,000", "$50,000", "$100,000", "$250,000", "$500,000 CSL or More", "Not Sure"]
  end

  def auto_bodily_injury_per_accident_collection
    ["$50,000", "$100,000", "$300,000", "$500,000 CSL or More", "Not Sure"]
  end

  def auto_property_damage_collection
    ["$25,000", "$50,000", "$100,000", "$500,000 CSL or More", "Not Sure"]
  end
  
  def auto_comprehensive_deductible_collection
    ["$100", "$250", "$500", "$1000", "$2000", "Not Sure"]
  end

  def auto_collision_deductible_collection
    ["$250", "$500", "$1000", "$2000", "Not Sure"]
  end

  def quote_types
    [
      { type: "PropertyQuote", name: "Property" },
      { type: "AutoQuote", name: "Auto" },
      { type: "CommercialQuote", name: "Commercial" },
      { type: "LifeInsuranceQuote", name: "Life" },
      { type: "HealthInsuranceQuote", name: "Health" },
      { type: "MotorcycleQuote", name: "Motorcycle" }, 
      { type: "FloodInsuranceQuote", name: "Flood" },
      { type: "BoatQuote", name: "Boat & Watercraft" },
      { type: "CondoQuote", name: "Condo" },
      { type: "LandlordQuote", name: "Landlord" },
      { type: "RentersQuote", name: "Renters" },
      { type: "JewelryQuote", name: "Jewelry" }
    ]
  end
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/whoweare_helper.rb
module WhoweareHelper
end

app/views/admin/quotes/_show.html.erb
<ul>
  <li><strong>Type: </strong> <%= quote.type.underscore.titleize %></li>
  <li><strong>Name: </strong> <%= quote.name %></li>
  <li><strong>Email: </strong> <%= quote.email %></li>
  <li><strong>Phone: </strong> <%= quote.phone %></li>
  <%= render "quote_mailer/#{quote.type.underscore}", quote: quote %>
  <li><strong>Additional Info: </strong> <%= quote.additional_info %></li>
  <li><strong>Interested in Life Insurance as well? </strong> <%= quote.interested_in_life_insurance %></li>
  <% if quote.current_policy.present? %>
    <li>
      <strong>Current Policy: </strong>
      <a target="_blank" href="<%= quote.current_policy.url %>"><%= quote.current_policy.file.filename %></a>
    </li>
  <% end %>
</ul>

app/views/quotes/_auto_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path, html: { "ng-cloak" => true, "ng-controller" => "AutoQuoteController", "ng-init" => "init(#{@quote.to_json(include: {drivers: { methods: [:errors] }, vehicles: { methods: [:errors] }})})" } do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :street_address, label: false %>
    <%= f.input :street_address2, label: false %>
    <%= f.input :city, label: false %>
    <%= f.input :zipcode, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <%= f.input :auto_current_insurance_carrier, label: false %>
    <%= f.input :auto_current_insurance_expires, label: false %>
    
    <fieldset>
      <legend>Driver Information</legend>
      <label>Select Number of Drivers</label>
      <select ng-model="drivers_count">
        <option value="0">0</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <div ng-repeat="driver in quote.drivers">
        <hr>
        Driver {{ $index + 1 }}
        <div class="input required">
          <input class="string required" placeholder="First Name" type="text" name="quote[drivers_attributes][{{$index}}][first_name]" id="quote_driver_{{$index}}_first_name" ng-model="driver.first_name">
          <span class="error" ng-show="driver.errors.first_name">{{ driver.errors.first_name[0] }}</span>
        </div>
        <div class="input required">
          <input class="string required" placeholder="Last Name" type="text" name="quote[drivers_attributes][{{$index}}][last_name]" id="quote_driver_{{$index}}_last_name" ng-model="driver.last_name">
          <span class="error" ng-show="driver.errors.last_name">{{ driver.errors.last_name[0] }}</span>
        </div>
        <div class="input">
          <select class="" name="quote[drivers_attributes][{{$index}}][gender]" id="quote_driver_{{$index}}_gender" ng-model="driver.gender">
            <option value="">Gender</option>
            <option value="M">Male</option>
            <option value="F">Female</option>
          </select>
        </div>
        <div class="input">
          <select class="" name="quote[drivers_attributes][{{$index}}][marital_status]" id="quote_driver_{{$index}}_marital_status" ng-model="driver.marital_status">
            <option value="">Marital Status</option>
            <option value="Single">Single</option>
            <option value="Married">Married</option>
          </select>
        </div>
        <div class="input">
          <input class="string required" placeholder="Date of Birth" type="text" name="quote[drivers_attributes][{{$index}}][date_of_birth]" id="quote_driver_{{$index}}_date_of_birth" ng-model="driver.date_of_birth">
        </div>
        <div class="input">
          <input class="string required" placeholder="Driver's License #" type="text" name="quote[drivers_attributes][{{$index}}][license_number]" id="quote_driver_{{$index}}_license_number" ng-model="driver.license_number">
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Vehicle Information</legend>
      <label>Select Number of Vehicles</label>
      <select ng-model="vehicles_count">
        <option value="0">0</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <div ng-repeat="vehicle in quote.vehicles">
        <hr>
        Vehicle {{ $index + 1 }}
        <div class="input required">
          <input class="string required" placeholder="VIN or Year/Make/Model" type="text" name="quote[vehicles_attributes][{{$index}}][vin]" id="quote_vehicle_{{$index}}_vin" ng-model="vehicle.vin">
        </div>
        <input class="string required" type="hidden" name="quote[vehicles_attributes][{{$index}}][driver_name]" id="quote_vehicle_{{$index}}_driver_name" ng-value="vehicle.driver_name">

        <div class="input required">
          <select ng-options="driver_name as driver_name for driver_name in allDriverNames()" ng-model="vehicle.driver_name">
            <option value="">Primary Driver</option>
          </select>
        </div>
        <div class="input">
          <select class="" name="quote[vehicles_attributes][{{$index}}][usage]" id="quote_vehicle_{{$index}}_usage" ng-model="vehicle.usage">
            <option value="">Usage</option>
            <option value="Work/School Commute">Work/School Commute</option>
            <option value="Pleasure">Pleasure</option>
            <option value="Business">Business</option>
            <option value="Transportation Network">Transportation Network</option>
          </select>
        </div>
        <div class="input">
          <select class="" name="quote[vehicles_attributes][{{$index}}][approximate_miles_a_day]" id="quote_vehicle_{{$index}}_approximate_miles_a_day" ng-model="vehicle.approximate_miles_a_day">
            <option value="">Approx. Miles a Day</option>
            <option value="1-5 Miles">1-5 Miles</option>
            <option value="6-10 Miles">6-10 Miles</option>
            <option value="11-15 Miles">11-15 Miles</option>
            <option value="16-20 Miles">16-20 Miles</option>
            <option value="25+ Miles">25+ Miles</option>
            <option value="No Commute">No Commute</option>
          </select>
        </div>
      </div>
    </fieldset>

    <%= f.input :auto_bodily_injury_per_person, label: false, as: :select, collection: auto_bodily_injury_per_person_collection, prompt: t("simple_form.placeholders.defaults.auto_bodily_injury_per_person") %>
    <%= f.input :auto_bodily_injury_per_accident, label: false, as: :select, collection: auto_bodily_injury_per_accident_collection, prompt: t("simple_form.placeholders.defaults.auto_bodily_injury_per_accident") %>
    <%= f.input :auto_property_damage, label: false, as: :select, collection: auto_property_damage_collection, prompt: t("simple_form.placeholders.defaults.auto_property_damage") %>
    <%= f.input :auto_roadside_assistance, label: false, as: :select, collection: yes_no_collection, prompt: t("simple_form.placeholders.defaults.auto_roadside_assistance") %>
    <%= f.input :auto_rental_car, label: false, as: :select, collection: ["Reimbursement", "No Reimbursement"], prompt: t("simple_form.placeholders.defaults.auto_rental_car") %>
    <%= f.input :auto_comprehensive_deductible, label: false, as: :select, collection: auto_comprehensive_deductible_collection, prompt: t("simple_form.placeholders.defaults.auto_comprehensive_deductible") %>
    <%= f.input :auto_collision_deductible, label: false, as: :select, collection: auto_collision_deductible_collection, prompt: t("simple_form.placeholders.defaults.auto_collision_deductible") %>
    <div class="input">
      <input type="hidden" name="quote[auto_discounts]" id="quote_auto_discounts" ng-value="quote.auto_discounts">
      <select ng-options="discount as discount for discount in allDiscounts" ng-model="selectedDiscounts" class="discount" multiple>
        <option value="">Discounts (select all that apply)</option>
      </select>
    </div>
    <div ng-if="isCollegeGrad()">
      <%= f.input :auto_college_graduated_from, label: false %>  
    </div>
    <%= f.input :auto_current_occupation, label: false %>

    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_boat_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

      <fieldset>
        <legend>Watercraft #1</legend>
        <%= f.input :boat_year, label: false %>
        <%= f.input :boat_make, label: false %>
        <%= f.input :boat_model, label: false %>
        <%= f.input :boat_year_purchased, label: false %>
        <%= f.input :boat_location_zipcode, label: false %>
        <%= f.input :boat_usage, label: false %>

      </fieldset>
    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_commercial_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path, html: { "ng-cloak" => true, "ng-controller" => "CommercialQuoteController", "ng-init" => "init(#{@quote.to_json})" } do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :street_address, label: false %>
    <%= f.input :street_address2, label: false %>
    <%= f.input :city, label: false %>
    <%= f.input :zipcode, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <%= f.input :commercial_business_type, label: false %>
    <div class="input">
      <input type="hidden" name="quote[commercial_type_of_insurance]" id="quote_commercial_type_of_insurance" ng-value="quote.commercial_type_of_insurance">
      <select ng-options="insuranceType as insuranceType for insuranceType in insuranceTypes" ng-model="selectedInsuranceTypes" class="quote_commercial_type_of_insurance" multiple>
        <option value="">Type of Insurance (Select all that apply)</option>
      </select>
    </div>

    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_condo_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path, html: { "ng-cloak" => true, "ng-controller" => "PropertyQuoteController", "ng-init" => "init(#{@quote.to_json(include: {additional_insureds: { methods: [:errors] }})})" } do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :name_of_insured, label: false %>
    <%= f.input :date_of_birth, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>
    <%= f.input :street_address, label: false %>
    <%= f.input :street_address2, label: false %>
    <%= f.input :city, label: false %>
    <%= f.input :zipcode, label: false %>
    <%= f.input :property_occupancy_type, label: false, as: :select, collection: ["Primary Residence", "Secondary Residence (Vacation Home)", "Tenant Occupied", "Vacation/Short Term Rental", "Vacant/Course of Construction"], prompt: t("simple_form.placeholders.defaults.property_occupancy_type") %>
    <%= f.input :property_dogs_on_property, label: false, as: :select, collection: yes_no_collection, prompt: t("simple_form.placeholders.defaults.property_dogs_on_property") %>
    <fieldset>
      <label>Additional Insureds</label>
      <select ng-model="additional_insureds_count">
        <option value="0">0</option>
        <option value="1">1</option>
        <option value="2">2</option>
      </select>
      <div ng-repeat="additional_insured in quote.additional_insureds">
        <hr>
        Additional Insured #{{ $index + 1 }}
        <div class="input required">
          <input class="string required" placeholder="Name" type="text" name="quote[additional_insureds_attributes][{{$index}}][name]" id="quote_additional_insured_{{$index}}_name" ng-model="additional_insured.name">
          <span class="error" ng-show="additional_insured.errors.name">{{ additional_insured.errors.name[0] }}</span>
        </div>
        <div class="input required">
          <input class="string required" placeholder="Birthday" type="text" name="quote[additional_insureds_attributes][{{$index}}][birthday]" id="quote_additional_insured_{{$index}}_birthday" ng-model="additional_insured.birthday">
          <span class="error" ng-show="additional_insured.errors.birthday">{{ additional_insured.errors.birthday[0] }}</span>
        </div>
      </div>
    </fieldset>
    <%= f.input :property_college_graduated, label: false, as: :select, collection: yes_no_collection, prompt: t("simple_form.placeholders.defaults.property_college_graduated"), input_html: { "ng-model" => "quote.property_college_graduated" } %>
    <div ng-show="quote.property_college_graduated == 'Yes'">
      <%= f.input :property_degree, label: false %>
      <%= f.input :property_occupation, label: false %>
    </div>

    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_flood_insurance_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <fieldset>
      <legend>Property Address</legend>
      <%= f.input :street_address, label: false %>
      <%= f.input :street_address2, label: false %>
      <%= f.input :city, label: false %>
      <%= f.input :zipcode, label: false %>
    </fieldset>

    <fieldset>
      <legend>Additional Information</legend>
      <%= f.input :flood_is_primary_home, label: false, as: :select, collection: yes_no_collection, prompt: t("simple_form.placeholders.defaults.flood_is_primary_home") %>

    </fieldset>

    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_health_insurance_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :street_address, label: false %>
    <%= f.input :street_address2, label: false %>
    <%= f.input :city, label: false %>
    <%= f.input :zipcode, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <fieldset>
      <legend>Additional Information</legend>
      <%= f.input :date_of_birth, label: false %>
      <%= f.input :gender, label: false, as: :select, collection: gender_collection, prompt: t("simple_form.placeholders.defaults.gender") %>
      <%= f.input :health_self_employed, label: false, as: :select, collection: yes_no_collection, prompt: t("simple_form.placeholders.defaults.health_self_employed") %>
      <%= f.input :health_expected_annual_household_income, label: false %>
      <%= f.input :health_number_of_people_in_household, label: false %>

    </fieldset>

    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_jewelry_quote_form.html.erb
<% content_for :quote_form do %>

  <%= simple_form_for @quote, as: :quote, url: quotes_path, html: { "ng-cloak" => true, "ng-controller" => "JewelryQuoteController", "ng-init" => "init(#{@quote.to_json(include: {valuable_items: { methods: [:errors] }})})" } do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <fieldset>
      <label>Valuable Items</label>
      <select ng-model="valuable_items_count">
        <option value="0">0</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <div ng-repeat="valuable_item in quote.valuable_items">
        <hr>
        Item #{{ $index + 1 }}
        <div class="input required">
          <input class="string required" placeholder="Zip Code" type="text" name="quote[valuable_items_attributes][{{$index}}][zip_code]" id="quote_valuable_item_{{$index}}_zip_code" ng-model="valuable_item.zip_code">
          <span class="error" ng-show="valuable_item.errors.zip_code">{{ valuable_item.errors.zip_code[0] }}</span>
        </div>
        <div class="input required">
          <input class="string required" placeholder="Estimated Value" type="text" name="quote[valuable_items_attributes][{{$index}}][estimated_value]" id="quote_valuable_item_{{$index}}_estimated_value" ng-model="valuable_item.estimated_value">
          <span class="error" ng-show="valuable_item.errors.estimated_value">{{ valuable_item.errors.estimated_value[0] }}</span>
        </div>
      </div>
    </fieldset>

    <%= render "quotes/additional_info_and_final_inputs", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_landlord_quote_form.html.erb
<% content_for :quote_form do %>

  <%= simple_form_for @quote, as: :quote, url: quotes_path do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :name_of_insured, label: false %>
    <%= f.input :date_of_birth, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <fieldset>
      <legend>Property Address</legend>
      <%= f.input :street_address, label: false %>
      <%= f.input :street_address2, label: false %>
      <%= f.input :city, label: false %>
      <%= f.input :zipcode, label: false %>
    </fieldset>
    

    <%= render "quotes/additional_info_and_final_inputs.html", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_life_insurance_quote_form.html.erb
<% content_for :quote_form do %>

  <%= simple_form_for @quote, as: :quote, url: quotes_path do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :first_name, label: false %>
    <%= f.input :last_name, label: false %>
    <%= f.input :street_address, label: false %>
    <%= f.input :street_address2, label: false %>
    <%= f.input :city, label: false %>
    <%= f.input :zipcode, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <fieldset>
      <legend>Additional Information</legend>
      <%= f.input :date_of_birth, label: false %>
      <%= f.input :gender, label: false, as: :select, collection: gender_collection, prompt: t("simple_form.placeholders.defaults.gender") %>
      <%= f.input :height, label: false %>
      <%= f.input :weight, label: false %>
      <%= f.input :life_tobacco_used, label: false, as: :select, collection: yes_no_collection, prompt: t("simple_form.placeholders.defaults.life_tobacco_used") %>

    </fieldset>

    <fieldset>
      <legend>Type of Insurance</legend>
      <%= f.input :life_term, label: false %>
      <%= f.input :life_coverage_amount, label: false %>
    </fieldset>

    <%= f.input :additional_info, label: false %>
    <%= f.input :current_policy %>
    <%= f.hidden_field :current_policy_cache %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>

app/views/quotes/_renters_quote_form.html.erb
<% content_for :quote_form do %>
  <%= simple_form_for @quote, as: :quote, url: quotes_path do |f| %>
    <%= f.input :type, as: :hidden %>
    <%= f.input :name_of_insured, label: false %>
    <%= f.input :date_of_birth, label: false %>
    <%= f.input :phone, label: false %>
    <%= f.input :email, label: false %>

    <fieldset>
      <legend>Property Address</legend>
      <%= f.input :street_address, label: false %>
      <%= f.input :street_address2, label: false %>
      <%= f.input :city, label: false %>
      <%= f.input :zipcode, label: false %>
    </fieldset>
    

    <%= render "quotes/additional_info_and_final_inputs.html", f: f %>

    <%= f.button :submit, "Get Quote", class: "" %>
  <% end %>
<% end %>