config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	get "insurance" => "insurance#home"
	namespace :insurance do 
		get "auto"
		get "commercial"
		get "life" 
		get "health" 
		get "motorcycle"
		get "flood" 
		get "boat"
		get "condo"
		get "renters" 
		get "landlord" 
		get "jewelry"
	end 

	get "quote" => 'quote#index'

	get "whoweare" => 'whoweare#index'
			
	get 'welcome/index'
	root 'welcome#index'

	resources :quotes, only: [:create]
end

app/models/additional_insured.rb
class AdditionalInsured < ActiveRecord::Base
  belongs_to :quote, inverse_of: :additional_insureds
  validates :name, :birthday, presence: true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auto_quote.rb
class AutoQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/boat_quote.rb
class BoatQuote < Quote
  validates :first_name, :last_name, presence: true
end

app/models/commercial_quote.rb
class CommercialQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, :commercial_business_type, presence: true
end

app/models/condo_quote.rb
class CondoQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :quote, inverse_of: :drivers
  validates :first_name, :last_name, presence: true
end

app/models/jewelry_quote.rb
class JewelryQuote < Quote
  validates :first_name, :last_name, presence: true
end

app/models/landlord_quote.rb
class LandlordQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/life_insurance_quote.rb
class LifeInsuranceQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/motorcycle_quote.rb
class MotorcycleQuote < Quote
  validates :first_name, :last_name, :street_address, :city, :zipcode, presence: true
end

app/models/property_quote.rb
class PropertyQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_many :drivers, inverse_of: :quote
  has_many :vehicles, inverse_of: :quote
  has_many :additional_insureds, inverse_of: :quote
  has_many :valuable_items, inverse_of: :quote

  strip_attributes
  validates :email, :phone, presence: true


  mount_uploader :current_policy, CurrentPolicyUploader
  
  after_create :notify_email

  def pretty_date
    created_at.strftime("%m/%d/%Y")
  end

  accepts_nested_attributes_for :drivers, :vehicles, :additional_insureds, :valuable_items

  def name
    if name_of_insured.present?
      name_of_insured
    else
      "#{first_name} #{last_name}"
    end
  end

  def pretty_date
    created_at.strftime('%m-%d-%Y')
  end

private
  # Send a notification email
  def notify_email
    begin
      QuoteMailer.send_email(self).deliver
    rescue => e
      Rails.logger.error("Unable to send quote email notification. #{e.message}")
    end
  end
end

app/models/renters_quote.rb
class RentersQuote < Quote
  validates :name_of_insured, :street_address, :city, :zipcode, presence: true
end

app/models/valuable_item.rb
class ValuableItem < ActiveRecord::Base
  belongs_to :quote, inverse_of: :valuable_items
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :quote, inverse_of: :vehicles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  
  before_action :set_quote_form_referer

  def set_quote_form_referer
    if request.get?
      if request.env['PATH_INFO'] == "/quote"
        session[:in_quote_form] = true
      else
        session[:in_quote_form] = nil
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def phone_number_link(text)
    sets_of_numbers = text.scan(/[0-9]+/)
    number = "+1-#{sets_of_numbers.join('-')}"
    link_to text, "tel:#{number}"
  end

  def gender_collection
    ["Male", "Female"]
  end

  def yes_no_collection
    ["Yes", "No"]
  end

  def auto_bodily_injury_per_person_collection
    ["$25,000", "$50,000", "$100,000", "$250,000", "$500,000 CSL or More", "Not Sure"]
  end

  def auto_bodily_injury_per_accident_collection
    ["$50,000", "$100,000", "$300,000", "$500,000 CSL or More", "Not Sure"]
  end

  def auto_property_damage_collection
    ["$25,000", "$50,000", "$100,000", "$500,000 CSL or More", "Not Sure"]
  end
  
  def auto_comprehensive_deductible_collection
    ["$100", "$250", "$500", "$1000", "$2000", "Not Sure"]
  end

  def auto_collision_deductible_collection
    ["$250", "$500", "$1000", "$2000", "Not Sure"]
  end

  def quote_types
    [
      { type: "PropertyQuote", name: "Property" },
      { type: "AutoQuote", name: "Auto" },
      { type: "CommercialQuote", name: "Commercial" },
      { type: "LifeInsuranceQuote", name: "Life" },
      { type: "HealthInsuranceQuote", name: "Health" },
      { type: "MotorcycleQuote", name: "Motorcycle" }, 
      { type: "FloodInsuranceQuote", name: "Flood" },
      { type: "BoatQuote", name: "Boat & Watercraft" },
      { type: "CondoQuote", name: "Condo" },
      { type: "LandlordQuote", name: "Landlord" },
      { type: "RentersQuote", name: "Renters" },
      { type: "JewelryQuote", name: "Jewelry" }
    ]
  end
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/whoweare_helper.rb
module WhoweareHelper
end

app/views/application/_footer.html.erb
<footer class="footer-2" role="contentinfo">
  <div class="footer-wrapper">
    <div class="footer-logo">
      <%= image_tag "logo_m.svg", :alt => "Logo" %>
    </div>
    <ul class="licensing">
      <li><strong>Licensing:</strong></li>
      <li><strong>AZ</strong> - 1089975</li>
      <li><strong>CA</strong> - 10I96581</li>
      <li><strong>CO</strong> - 460681</li>
      <li><strong>FL</strong> - W216194</li>
      <li><strong>OR</strong> - 100265964</li>
      <li><strong>TX</strong> - 2020888</li>
    </ul>
    <div class="footer-secondary-links">
      <ul>
        <li>              
          <a href="https://www.google.com/maps/place/450+Newport+Center+Dr+%23200,+Newport+Beach,+CA+92660/data=!4m2!3m1!1s0x80dce085fee61a87:0x3fa1f137a4b359aa?sa=X&ved=0ahUKEwj_96nP3MvNAhUGwWMKHR-9BskQ8gEIHTAA" target="_blank">450 Newport Center Drive Suite 200 Newport Beach, CA 92660</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/application/_nav.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
   <a href="/" class="logo">
      <%= image_tag "navigation/color_logo.svg" %>
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link">
          <%= link_to "Who We Are", whoweare_path %>
        </li>
        <li class="nav-link phone-nav">
          <%= phone_number_link("(888) 722-6411") %>
        </li>
        <li id="js-navigation-more" class="nav-link more"><a href="javascript:void(0)">What We Cover</a>
          <ul class="submenu">
              <li class="small-nav">
                <%= link_to "Property", insurance_path %>
              </li>
              <li class="small-nav"> 
                <%= link_to "Auto", insurance_auto_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Commercial", insurance_commercial_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Life", insurance_life_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Health", insurance_health_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Motorcycle", insurance_motorcycle_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Flood", insurance_flood_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Boat & Watercraft", insurance_boat_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Condo", insurance_condo_path%>
              </li>
              <li class="small-nav">
                <%= link_to "Landlord", insurance_landlord_path %>
              </li>
              <li class="small-nav">
                <%= link_to "Renters", insurance_renters_path %>     
              </li>
              <li class="small-nav">
                <%= link_to "Jewelry", insurance_jewelry_path %>
              </li>
          </ul>
        </li>
        <li class="nav-link">
          <%= link_to "Get A Quote", quote_path %>
        </li>
      </ul>
    </nav>
  </div>
</header>